package org.homework.analyzer;

/**
 * Represents the count of a given word.
 *
 * @see TextAnalysisResult
 */
public class WordCount {

	private String word;
	private int count;

	WordCount(String word, int count) {
		this.word = word;
		this.count = count;
	}

	void increment() {
		count = count + 1;
	}

	/**
	 * @return the word
	 */
	public String getWord() {
		return word;
	}

	/**
	 * @return number of occurrences of the word
	 */
	public int getCount() {
		return count;
	}


	// Generated by IntelliJ. Useful for tests and debugging.

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (!(o instanceof WordCount)) return false;

		WordCount wordCount = (WordCount) o;

		if (count != wordCount.count) return false;
		return word.equals(wordCount.word);
	}

	@Override
	public String toString() {
		return "WordCount{" +
				"word='" + word + '\'' +
				", count=" + count +
				'}';
	}

}
